### ISSUE TITLE
Document TemplateHaskell debug block restrictions

### ISSUE THREAD

**Issue by marklnichols** [ndmitchell/debug#11]
This code causes a compile error: 

-- (The first line is line 84)
debug [d|
    f :: Int -> Int
    f n = g n  * h n 
    |]

debug [d|
    g :: Int -> Int
    g n = n * 3
    |]

h :: Int -> Int 
h n = n + 2

:\stack_root\haskell-examples\src\ProjectEuler\Problem19.hs:84:1: error:
    * Variable not in scope: g :: t -> a
    * `g' (splice on lines 89-92) is not in scope before line 89

C:\stack_root\haskell-examples\src\ProjectEuler\Problem19.hs:84:1: error:
    * Variable not in scope: h :: t -> a
    * `h' (line 95) is not in scope before the splice on lines 89-92
    
Is this calling functions from block to block legitimate and fixable? Or just something that needs to 
be avoided and documented?

**Comment by ndmitchell** [comment]
This is a TemplateHaskell limitation - a block can’t use things after it in the same file - so if you reorder them it will work. Certainly needs recording somewhere, since it’s a non obvious limitation and I think can be triggered even if g isn’t in a block.

**Comment by marklnichols** [comment]
Ok - when I get a chance I was going to add a couple of things to the documentation re what wasn't immediately clear to me -- I can add a note about this as well.

**Comment by ndmitchell** [comment]
Makes sense - I'm leaving the ticket open to capture that documentation requirement.

**Comment by marklnichols** [comment]
I have a small update to the docs that includes this.  Can you give me whatever access rights are required to push please?  Currently I get a 403.

**Comment by ndmitchell** [comment]
The standard way to contribute to GitHub is fork (create your own local copy) and pull request (send me the changes through github). I do both those on the web UI.

**Comment by marklnichols** [comment]
Ok, I'm getting on the road now, I'll do it when I get home.

**Comment by ndmitchell** [comment]
Great - it's the standard github workflow that every project uses nowadays, so definitely worth learning.

**Comment by marklnichols** [comment]
This is done, closing this.

**Comment by ndmitchell** [comment]
Thanks!
