### ISSUE TITLE
Browser back and forward buttons don't work

### ISSUE THREAD

**Issue by pepeiborra** [ndmitchell/debug#13]
The html frontend should build a history of visited function calls during a debugging session.

**Comment by pepeiborra** [comment]
Tested in Chrome and Safari, don't work in either.

**Comment by ndmitchell** [comment]
It doesn't work deliberately. It also can't work when hosted as a file on the local file system, as the browser methods to do it only work over `http`. Furthermore, is it really a useful feature? If forward/back do make sense they could be implemented in the HTML itself.

**Comment by pepeiborra** [comment]
It is a reasonably useful feature imho when navigating the call stack.

**Comment by ndmitchell** [comment]
I have a better idea for a visualisation for the call stack. Let's use this ticket to improve that visualisation, hopefully after which you will not want forward/back buttons.

**Comment by pepeiborra** [comment]
Sure, but I am skeptical. No matter how the call stack is rendered, I suspect that navigating it will want for back/forward controls.
