### ISSUE TITLE
Use typed Javascript

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/debug#17]
And also the opaque types trick: https://codemix.com/opaque-types-in-javascript/

**Comment by pepeiborra** [comment]
Have you considered Purescript ? I suspect it would be far more likely to attract contributors.

**Comment by ndmitchell** [comment]
Is that based on personal experience or just knowledge of the general communities? Having tried both, it seems Purescript is a nightmare to setup and only starts to shine in larger programs - if you just want fairly simple DOM manipulation then TypeScript with it's close-to-Javascript feel seems like an advantage. But happy to hear alternative viewpoints.

**Comment by pepeiborra** [comment]
I don't really have hands on experience with either Purescript or Typescript. I wasn't aware that Purescript is hard to set up. My reasoning was that Purescript seems more likely to attract contributors than a typed superset of Javascript because debug is a Haskell package.

**Comment by pepeiborra** [comment]
I have been writing a PureScript port on the side and am currently halfway through.

**Comment by ndmitchell** [comment]
An existence proof of something working nicely in purescript would certainly convince me - I look forward to it, and certainly won't be doing anything on this until your experiments have concluded.

**Comment by pepeiborra** [comment]
Can close this now that we have switched to Elm for the frontend

**Comment by ndmitchell** [comment]
Yep
