### ISSUE TITLE
Function param names missing

### ISSUE THREAD

**Issue by marklnichols** [ndmitchell/debug#25]
For example, with this function
```
debug [d|
    lcm_gcd :: (Integral a) => a -> a -> Double
    lcm_gcd x y =
        let least = lcm x y
        in fromIntegral least ^^ gcd x y
    |]
```

We still get $arg1 and $arg2, but x and y are missing.

**Comment by pepeiborra** [comment]
I will eventually take a look at this since it's probably my fault, but my life would be much easier if there was a failing test.

**Comment by pepeiborra** [comment]
This stopped working because of 272f8ad676fb66e22d1ea65f81827dc75a15d381 which was intended as a fix for list comprehensions. I'll roll it back and create a separate issue for list comps.

**Comment by marklnichols** [comment]
I'd like to have some automated tests as well.  It's not clear to me how to do this...

**Comment by pepeiborra** [comment]
You can follow the approach I've taken in https://github.com/ndmitchell/debug/pull/30
