### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by pepeiborra** [ndmitchell/debug#38]
What do we need to make a release ? The number of new features and improvements since 0.1 is huge.

**Comment by ndmitchell** [comment]
I need to take a wander through the code and try it out - I've mostly been merging from you and keeping the tests inline - so I'm not really sure what state it is in. I'm off to Zurich tomorrow morning, but will hopefully grab some time there to take a closer look, then release next weekend. Does that work for you?

**Comment by pepeiborra** [comment]
Have your wander first and let's take it from there.

**Comment by marklnichols** [comment]
I have a couple of useful additions that are now working, but it might not be until later today I can get the PR put together.  If you can hold off on a release...

**Comment by ndmitchell** [comment]
It's taking too long for the release. I suggest we do it Wednesday night regardless, with whatever state it's in, and we can always do more releases (fortunately version numbers are infinite). I hope to wander through before then, but if I don't, then tough luck on me.

**Comment by ndmitchell** [comment]
Done! And only a few days later than I hoped, with a lot less reviewing than I wanted (but I did check it still basically works).
