### ISSUE TITLE
GHCi error

### ISSUE THREAD

**Issue by marklnichols** [ndmitchell/debug#41]
stack init
stack build
stack ghci

gives:
Loaded GHCi configuration from <my directory>\debug\.ghci

<no location info>: error:
    module `main:DebugPP' is defined in multiple files

**Comment by ndmitchell** [comment]
Our `.ghci` file loads a lot of stuff, which causes things to be loaded twice. It's all a bit ugly really, and arguably a GHC bug that loading the same file twice is not idempotent, but that's going to be a long way off. Easiest way out for now it just run `stack ghci --no-load`. In `ghcid` we do this automatically if a directory has a `.ghci` file, so it's a pretty standard thing to do.
