### ISSUE TITLE
Limit number of "shadowed" variables

### ISSUE THREAD

**Issue by marklnichols** [ndmitchell/debug#51]
Situations like this are a problem if the list is larger than a few elements:

![image](https://user-images.githubusercontent.com/16517726/36601807-156debb0-1884-11e8-880a-969c71890231.png)

I can put in a fix to limit the number of (') vars added, but we probably also need a way to show that there really were more values but they aren't being shown.

Something like this maybe:

    x'''(+) =  ...

**Comment by marklnichols** [comment]
The PR just submitted limits the number of 'shadowed' vars to 3, i.e. x, x', x'', x'''

We still need a way to show that the list of variables has been truncated.

**Comment by ndmitchell** [comment]
Do we? I think just not worrying might be the easiest and pragmatic solution for now...

**Comment by marklnichols** [comment]
Ok, sounds good then =)
